# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  cache: false
  globals:
    privacia_public_site_url: "%privacia_public_site_url%"
    privacia_public_store_url: "%privacia_public_store_url%"
    privacia_public_technical_service: "%privacia_public_technical_service%"

