services:
  _defaults: { public: true }


  paprec_catalog.postal_code_manager:
    class: Paprec\CatalogBundle\Service\PostalCodeManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.region_manager:
    class: Paprec\CatalogBundle\Service\RegionManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.product_manager:
    class: Paprec\CatalogBundle\Service\ProductManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.product_label_manager:
    class: Paprec\CatalogBundle\Service\ProductLabelManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.picture_manager:
    class: Paprec\CatalogBundle\Service\PictureManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.number_manager:
    class: Paprec\CatalogBundle\Service\NumberManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]


  twig.formatAmount:
    class: Paprec\CatalogBundle\Twig\Extension\FormatAmountExtension
    public: false
    arguments: ["@service_container"]
    tags:
      - { name: twig.extension }

  twig.formatId:
    class: Paprec\CatalogBundle\Twig\Extension\FormatIdExtension
    public: false
    arguments: ["@service_container"]
    tags:
      - { name: twig.extension }

  twig.productLabelTranslation:
    class: Paprec\CatalogBundle\Twig\Extension\ProductLabelTranslationExtension
    public: false
    arguments: ["@service_container"]
    tags:
      - { name: twig.extension }

parameters:

  paprec_catalog.product.picto_path: "%kernel.root_dir%/../web/uploads/pictos"

  paprec_types_picture:
    - PICTO
    - PICTURE
    - PILOTPICTURE

  paprec_languages:
    - DE
    - FR
    - IT
    - EN

  paprec_customizable_area_codes:
    - collectivite_top_msg
    - groupe_top_msg
    - particulier_top_msg
    - entreprise_top_msg
    - reassurance_banner_di
    - logo_banner_di
    - images_banner_di
    - reassurance_banner_chantier
    - logo_banner_chantier
    - images_banner_chantier
    - reassurance_banner_d3e
    - logo_banner_d3e
    - images_banner_d3e
    - logo_banner_default
    - reassurance_banner_default

