services:
#    commercial.example:
#        class: PaprecCommercialBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  paprec_commercial.quote_request_manager:
    class: Paprec\CommercialBundle\Service\QuoteRequestManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]


parameters:
  paprec_quote_status:
    - CREATED
    - PENDING
    - PROCESSING
    - CLOSED

  paprec_quote_access:
    - stairs
    - elevator
    - ground

  paprec_quote_staff:
    - '19'
    - '1019'
    - '2029'
    - '3039'
    - '4049'
    - '5059'
    - '6069'
    - '7079'
    - '8089'
    - '9099'
    - '100109'
    - '110119'
    - '120129'
    - '130139'
    - '140149'
    - '150+'
