services:
#    paprec_user.example:
#        class: Paprec\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  twig.paprec_has_access:
    class: Paprec\UserBundle\Twig\Extension\AccessExtension
    public: false
    arguments: ["@service_container", "@security.token_storage"]
    tags:
      - { name: twig.extension }